#ifndef _ENUMS_H
#define _ENUMS_H

enum GameModes {
 GAME_MODE_OVERWORLD = 0,
 GAME_MODE_JUNGLE_LAND_MENU = 1,
 GAME_MODE_SAVE_MENU = 2,
 GAME_MODE_LOAD_GAME_MENU = 3,
 GAME_MODE_DEMO = 4,
 GAME_MODE_DEMO_2 = 5,
 GAME_MODE_TITLE_SCREEN = 6,
 GAME_MODE_BATTLE_MENU = 7,
 GAME_MODE_OPTIONS_MENU = 8,
 GAME_MODE_GAME_OVER = 9,
 GAME_MODE_SUPPLY_SYSTEM_LOGO = 10,
 GAME_MODE_PRE_CREDITS = 11,
 GAME_MODE_NEW_GAME_MENU = 12,
 GAME_MODE_JUNGLE_LAND = 13,
 GAME_MODE_STAGE_SELECT = 14,
 GAME_MODE_UNK_15 = 15,
 GAME_MODE_RANKING = 16,
 GAME_MODE_BOOT = 18,
 GAME_MODE_SUNSOFT_LOGO = 19,
 GAME_MODE_CREDITS = 20,
 GAME_MODE_OPENING_CUTSCENE = 21
};

#endif